#cloud-config

package_update: true

bootcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg # for docker
  - |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

# create the docker group
groups:
  - docker

# assign a VM's default user, which is dockeruser, to the docker group
users:
  - default
  - name: dockeruser
    groups: docker

# create docker-compose.yaml. requires container registry authentication
write_files:
  - path: /app/docker-compose.yaml
    permissions: 0755
    content: |
      version: '3'
      services:
        pubsubdb:
          image: redis:latest
          restart: unless-stopped
          ports: 
            - "6379:6379"
          volumes:
            - redisdata:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
          command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        redisdata:
  - path: /app/redis.conf
    permissions: 0755
    content: |
      requirepass ${redis_password}


# start redis server
runcmd:
  - cd /app
  - docker compose up -d
